language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
install:
  - pip install -r dev_requirements.txt

script: nosetests
after_success:
  - pip install coveralls
  - coverage run --source=ordbok setup.py -q nosetests
  - coveralls